"""脚本生成器单元测试。

生成器负责把用例渲染成可读、可维护的 pytest 代码。模板负责结构、模型只负责填空 ——
这条设计决定了「生成的代码是不是能 review」。这里钉住渲染产物里的关键约定。
"""
from __future__ import annotations

import json

import pytest
from jinja2 import TemplateNotFound

from smarttest.generator import PytestGenerator
from smarttest.semantic.models import ScenarioCase


def make_scenario() -> ScenarioCase:
    return ScenarioCase.model_validate(
        {
            "scenario_id": "round_trip_createOrder_getOrder",
            "title": "创建订单后查询详情",
            "rationale": "consistency:round_trip:getOrder",
            "source": "rule",
            "steps": [
                {
                    "operation_id": "createOrder",
                    "body": {"product_id": "P001", "quantity": 1},
                    "expect_status": 201,
                    "capture": {"order_id": "$.order_id"},
                },
                {
                    "operation_id": "getOrder",
                    "path_params": {"order_id": "{{order_id}}"},
                    "expect_status": 200,
                    "expect_body": {"$.order_id": "{{order_id}}"},
                },
            ],
        }
    )


class TestContractRendering:
    def test_rendered_code_is_valid_python_and_carries_metadata(
        self, spec, engine, tmp_path
    ):
        cases = engine.generate(spec)
        path = PytestGenerator(base_url="http://127.0.0.1:8123").render_contract_tests(
            spec, cases, tmp_path
        )
        code = path.read_text(encoding="utf-8")
        assert f"用例总数 : {len(cases)}" in code
        assert "AUTO-GENERATED by SmartTest" in code
        compile(code, str(path), "exec")  # 生成的必须是合法 Python

    def test_conftest_provides_a_client_fixture(self, tmp_path):
        path = PytestGenerator().render_conftest(tmp_path)
        code = path.read_text(encoding="utf-8")
        assert "def client()" in code
        assert "httpx.Client" in code

    def test_unknown_template_raises(self, tmp_path):
        with pytest.raises(TemplateNotFound):
            PytestGenerator().render_business_tests(tmp_path, "no_such_template.j2", {})


class TestScenarioRendering:
    def test_scenarios_are_written_as_data_next_to_the_code(self, spec, engine, tmp_path):
        generator = PytestGenerator(base_url="http://127.0.0.1:8123")
        generator.render_contract_tests(spec, engine.generate(spec), tmp_path)  # 先建立 operationId 索引

        path = generator.render_scenario_tests(
            [make_scenario()], tmp_path, provider_name="rule-based"
        )

        data = json.loads((tmp_path / "scenarios.json").read_text(encoding="utf-8"))
        assert data[0]["scenario_id"] == "round_trip_createOrder_getOrder"
        assert data[0]["steps"][0]["method"] == "POST"
        # 路径参数先解析成真实 URL；变量留给运行期替换
        assert data[0]["steps"][1]["path"] == "/api/v1/orders/{{order_id}}"
        assert data[0]["steps"][1]["method"] == "GET"
        assert "rule-based" in path.read_text(encoding="utf-8")

    def test_degraded_reason_is_rendered_into_the_header(self, spec, engine, tmp_path):
        generator = PytestGenerator()
        generator.render_contract_tests(spec, engine.generate(spec), tmp_path)
        path = generator.render_scenario_tests(
            [make_scenario()], tmp_path, degraded_reason="模型接口返回 500"
        )
        assert "模型接口返回 500" in path.read_text(encoding="utf-8")


class TestBusinessRendering:
    def test_context_is_passed_through_to_the_template(self, tmp_path):
        path = PytestGenerator(base_url="http://127.0.0.1:9999").render_business_tests(
            tmp_path,
            "business_test.py.j2",
            {
                "products": [{"product_id": "P001", "price": 399.0}],
                "default_product_id": "P001",
            },
        )
        code = path.read_text(encoding="utf-8")
        assert 'BASE_URL = "http://127.0.0.1:9999"' in code
        assert "'product_id': 'P001'" in code
        assert "'price': 399.0" in code
